DWS-Projekat/Models/Objava.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DWS_Projekat.Models
{
    public class Objava
    {
        public int Id { get; set; }
        public String Title { get; set; }
        public String Autor { get; set; }
        public String Content { get; set; }
        public String Slika { get; set; }
    }
}

DWS-Projekat/Controllers/ObjavaController.cs
using DWS_Projekat.Data;
using DWS_Projekat.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DWS_Projekat.Controllers
{
    public class ObjavaController : Controller
    {

        private readonly ApplicationDbContext _dbContext;
           
        public ObjavaController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index(int id)
        {
            var objava = _dbContext.Objave.FirstOrDefault(x => x.Id == id);
            var komentari = _dbContext.Replies.Where(x => x.Objavaid == id);
            ViewBag.objava = objava;
            ViewBag.komentari = komentari;
            return View();
        }

        [HttpPost]
        public IActionResult NapisiKomentar(int idobjave,string content)
        {
            var povrat = new Reply();
            povrat.Autor = this.HttpContext.User.Identity.Name;
            povrat.tekst = content;
            povrat.Objavaid = idobjave;

            _dbContext.Replies.Add(povrat);
            _dbContext.SaveChanges();
            return RedirectToAction("Index",new { id = idobjave });
        }

        [HttpPost]
        public IActionResult ObrisiKomentar(int idkomentara,int idobjave)
        {
            var page = _dbContext.Replies.FirstOrDefault(x => x.Id == idkomentara);
            _dbContext.Replies.Remove(page);
            _dbContext.SaveChanges();
            return RedirectToAction("Index", new { id = idobjave });
        }
    }
}

DWS-Projekat/Views/Objava/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager




<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

<div class="card mb-3">
    <img src="@ViewBag.objava.Slika" class="card-img-top" alt="..." style=" width: 100%; height: 19vw; object-fit: cover; ">
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><b>Autor objave: </b>@ViewBag.objava.Autor</li>
    </ul>
    <div class="card-body">
        <h5 class="card-title">
            @ViewBag.objava.Title
            @if (SignInManager.IsSignedIn(User) && User.IsInRole("Administrator"))
            {
                <a href="/admin/urediobjavu?id=@ViewBag.objava.Id" style="text-decoration:none; color:black;"><i class="fas fa-edit"></i></a>
            }
        </h5>
        <p class="card-text">@Html.Raw(ViewBag.objava.Content)</p>
    </div>
</div>

<div>
    <h4>Komentari:</h4>
    @foreach (var komentar in ViewBag.komentari)
    {
        <div class="media border p-3">
            <img src="https://www.w3schools.com/bootstrap4/img_avatar3.png" alt="John Doe" class="mr-3 mt-3 rounded-circle" style="width:60px;">
            <div class="media-body">
                <h6>
                    @komentar.Autor
                    @if (SignInManager.IsSignedIn(User) && User.IsInRole("Administrator"))
                    {
                        <form asp-controller="Objava" asp-action="ObrisiKomentar" method="post"
                              style="display:inline;">
                            <input value="@ViewBag.objava.Id" name="idobjave" type="hidden" />
                            <input value="@komentar.Id" name="idkomentara" type="hidden" />
                            <i class="fas fa-trash-alt" onclick='this.parentNode.submit(); return false;'></i>
                        </form>

                    }
                </h6>
                <p>@komentar.tekst</p>
            </div>
        </div>
    }
</div>


@if (SignInManager.IsSignedIn(User))
{
    <form asp-controller="Objava" asp-action="NapisiKomentar" method="post" class="mt-4">
        <input name="idobjave" type="hidden" value="@ViewBag.objava.Id" />
        <div class="form-group">
            <textarea name="content" class="form-control" rows="4"></textarea>
            <button type="submit" class="btn btn-primary mt-3 w-100">Objavi komentar</button>
        </div>
    </form>
}